# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.1.0
jobs:
  #test the app on circleci
  build_test:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r Pipfile
      - run:
          name: Run Tests
          command: |
            pytest


# Orchestrate or schedule a set of jobs
workflows:
  build_test_first:
    jobs:
      - build_test
