# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.1.0

jobs:
  #--- JOB 1: test the app on circleci ---#
  build_test:
    #use the circleci python 3.7 image to make pytest work
    docker:
      - image: circleci/python:3.7
    steps:
      #start by checking out the repo
      - checkout
      #then run the commands below to set up the virtual env in CircleCI
      #so that unit tests can be run
      - run:
          name: Install Python Dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: Run Unit Tests
          command: |
            pipenv run pytest

  #--- JOB 2: deploy to google app engine ---#
  gae_deploy:
    working_directory: ~/app/
    docker:
      - image: google/cloud-sdk:latest
    steps:
      -checkout
      #use the gcp orb
      - gcp-cli/initialize
      - run:
          name: Deploy to Google App Engine
          command: |
            gcloud --quiet app deploy /app/app.yaml

# ------- WORKFLOWS ------- #
workflows:
  #run the unit tests and deploy to gae if pass
  build_test_deploy:
    jobs:
      - build_test:
          #ensure we only deploy the master branch and not a dev branch
          filters:
            branches:
              only:
                - main

      - gae_deploy:
          #requires:
          #  - build_test
          filters:
            branches:
              only:
                - main
